-- Horizon initial schema (migration version 1)
--
-- Five tables: accounts, transactions, categories, milestones, recurring_transactions.
-- Monetary values are integers (cents). Dates are ISO YYYY-MM-DD strings. IDs are
-- UUID strings generated by the application via crypto.randomUUID().

CREATE TABLE accounts (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL,
  name TEXT NOT NULL,
  opening_balance INTEGER NOT NULL,
  opening_date TEXT NOT NULL,
  sondertilgung_allowance INTEGER
);

CREATE INDEX idx_accounts_kind ON accounts(kind);

CREATE TABLE transactions (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL,
  date TEXT NOT NULL,
  amount INTEGER NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  transfer_id TEXT,
  recurring_transaction_id TEXT
);

CREATE INDEX idx_transactions_account_id ON transactions(account_id);
CREATE INDEX idx_transactions_transfer_id ON transactions(transfer_id);
CREATE INDEX idx_transactions_date ON transactions(date);

CREATE TABLE categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  is_default INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE milestones (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  account_id TEXT NOT NULL,
  target_balance INTEGER NOT NULL
);

CREATE TABLE recurring_transactions (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL,
  amount INTEGER NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  frequency TEXT NOT NULL,
  day_of_month INTEGER NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  linked_account_id TEXT,
  month_of_year INTEGER
);

CREATE INDEX idx_recurring_transactions_account_id ON recurring_transactions(account_id);
CREATE INDEX idx_recurring_transactions_is_active ON recurring_transactions(is_active);

INSERT INTO categories (id, name, is_default) VALUES
  ('00000000-0000-4000-8000-000000000001', 'Income',         1),
  ('00000000-0000-4000-8000-000000000002', 'Housing',        1),
  ('00000000-0000-4000-8000-000000000003', 'Food',           1),
  ('00000000-0000-4000-8000-000000000004', 'Subscriptions',  1),
  ('00000000-0000-4000-8000-000000000005', 'Entertainment',  1),
  ('00000000-0000-4000-8000-000000000006', 'Investment',     1),
  ('00000000-0000-4000-8000-000000000007', 'Transfer',       1),
  ('00000000-0000-4000-8000-000000000008', 'Miscellaneous',  1);
